let dom = (tag, prop, ...args) => {   // function that handles the JSX after being transpiled
  let componentName = null            // this variable should later be set by the render function

  args.forEach((item, i) => {
    if(typeof args[i] === 'string') {
      args[i] = {tag: 'text', text: args[i]}
    }
  })
  if(typeof tag === 'object' && tag.isComponent) {
    tag.prop = prop
    //console.log(tag.render())
  }
  let obj = { tag: tag, componentName: componentName, prop: prop, children: args || [] } // the object tree generated by the given JSX
  return obj
}

export default dom
